steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
    - '-c'
    - docker run -t test01 bash /bin/bash -c 'cd / && touch test.txt'
- name: test01
  entrypoint: bash
  args:
    - '-c'
    - ls -al /
