steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - '-c'
    - gcloud secrets versions access latest --secret=main-server-production-env > .env
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - '-c'
    - gcloud app deploy --version ${BRANCH_NAME//./-} --no-cache
  env:
    - BRANCH_NAME=$BRANCH_NAME
